### ISSUE TITLE
На дисплее горит 8--0

### ISSUE THREAD

**Issue by tigran73** [AlexGyver/GyverMOD#3]
Подскажите что может быть. На дисплее горит 8--0. На кнопки не реагирует, а потом уходит в сон. Из сна просыпается 5 нажатиями. Корпуса пока нет, как и коннектора с атомайзером, но подсоединил вместо них спираль от HQD, мосфета такого же не нашел поставил IRF3205.

**Comment by tigran73** [comment]
Дисплей 3461bs1-7.3

**Comment by IlyaKangin** [comment]
пин для измерения акб подцепил?

**Comment by tigran73** [comment]
Проблему решил неправильно сделал калиьровку
